on: 
  workflow_dispatch:

# env:
#   greeting: "Hello"
#   name: "Dan"

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # - name: Install Python, pipenv and Pipfile packages
      #   uses: palewire/install-python-pipenv-pipfile@v2
      #   with:
      #     python-version: 3.9
      - uses: actions/checkout@v2 

      - run: pipx install "pipenv==2022.10.4"

      - uses: actions/setup-python@v3
        with:
         python-version: '3.9' 
         cache: 'pipenv'

      - run: pipenv install --deploy --dev

      # - name: Install Python dependencies
      #   run: python -m pip install --upgrade pip pipenv wheel

      # - id: cache-pipenv
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/.local/share/virtualenvs
      #     key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      # - name: Install dependencies
      #   if: steps.cache-pipenv.outputs.cache-hit != 'true'
      #   run: |
      #     pipenv install --deploy --dev

      # - run:  pipenv shell 

      - run: |
          pipenv sync --dev
          

      # - run: python --version
      # - run: pwd
      # - run: ls
      # - run: bash helloworld.sh
      # - run: ls -la .github/
      # - run: echo ${GITHUB_WORKSPACE}
      # - run: bash ${GITHUB_WORKSPACE}/.github/workflows/bash.sh
      - run: |
          which pip
          which pip3
          which pipenv
      - run: python3 ${GITHUB_WORKSPACE}/.github/workflows/python.py
      - run: echo $SHELL
    

